"""Remove bio field from users table

Revision ID: a3fad7168bb7
Revises: 88cbec274a2a
Create Date: 2025-07-18 17:54:34.549107

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'a3fad7168bb7'
down_revision: Union[str, None] = '88cbec274a2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'bio')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('bio', mysql.TEXT(), nullable=True))
    # ### end Alembic commands ###
